apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cartyx-data-prod
  namespace: flux-system
spec:
  # Promote only immutable revisions verified in dev.
  suspend: false
  interval: 1m
  url: https://github.com/biozal/cartyx-infrastructure.git
  ref:
    tag: data-v0.1.0
